---
title: "Final Grade Reflection"
author: "Jacky Wu"
format: pdf
editor: visual
---

# Final Reflection

I believe that my final grade I earned in this class is a B-.

## Learning Targets

### Working with Data

I demonstrated WD-1 in Lab 3 Setup at a proficient level. I demonstrated WD-2 in Lab 3 Problem 7 at a proficient level. I demonstrated WD-3 in Lab 3 Problem 8 Study Subjects and in Lab 9 Problem 10 at a moderate level. I demonstrated WD-4 in Lab 4 Problem 7, Challenge 4 Problem 1, and Challenge 8 Problem 4 at a proficient level. I demonstrated WD-5 in Challenge 4 Problem 1 at a proficient level. I demonstrated WD-6 in Lab 4 Set-up at a proficient level. I demonstrated WD-7 in Challenge 3 Problem 1 at a proficient level.

### Reproducibility

I demonstrated R-1 in Challenge 9 at a moderate level. I demonstrated R-2 in Lab 9 at a proficient level. I demonstrated R-3 in Lab 9 at a proficient level.

### Data Visualization & Summarization

I demonstrated DVS-1 in Challenge 3 Problem 1 and in Challenge 9 Problem 9 at a proficient level. I demonstrated DVS-2 in Challenge 9 Problem 9 at a proficient level. I demonstrated DVS-3 in Lab 4 Problem 7 and Challenge 9 Problem 9 at a moderate level. I demonstrated DVS-4 in Challenge 3 Problem 1 at a proficient level. I demonstrated DVS-5 in Lab 4 Problem 7 at a proficient level. I demonstrated DVS-6 in Challenge 9 Problem 2 at a proficient level. I demonstrated DVS-7 in Challenge 9 Problem 1 at a proficient level.

### Program Efficiency

I demonstrated PE-1 in Lab 5 at a moderate level. I demonstrate PE-2 in Challenge 8 Setup at a proficient level. I demonstrated PE-3 in Challenge 8 Problem 3 at a proficient level.

### Data Simulation & Modeling

I demonstrated DSM-1 in Practice Activity 9 Problem 3 at a proficient level. I demonstrated DSM-2 in Lab 9 Problem 5 and 6 at a proficient level.

## Continued Learning

I demonstrated continued learning by completing Challenges 3 and 4. I believe these challenges are where I demonstrated that I extended the skills I learned the best. Most of the other challenges tackled on making visualizations look better. In Challenge 3, I got to practice on using functions that I learned such as select, group_by, and mutate. In this challenge, I also got to finally practice pivoting data frames from long to wide and vise versa. In Challenge 4, I got to experience what data scientists do in the real world. I got to choose my own dataset to use as comparison to complete my analysis. This challenge also allowed me to practice joining different datasets in various ways.

## Revising My Thinking

I done several revisions, but the only revision where I felt that I improved the best that I could was on Lab 3. I was able to revise the three questions that had a G and turned it into a S. I also edited some code on some questions where you left comments where It wasn't necessary to revise.

## Peer Support

I did a poor job in demonstrating peer support. I was catching up on assignments throughout the whole quarter. This caused me to be unable to provide code feedback to my peers. I was only able to peer review code on the last lab. However, I did contribute in helping my group in class and tried to help others in the group with their code whenever I could.\
